### ISSUE TITLE
BODY 21A not found

### ISSUE THREAD

**Issue by rirri93** [soulslicer/STAF#23]
I can't run demo. With this command `build/examples/openpose/openpose.bin --model_pose BODY_21A --tracking 1 --render_pose 1` I obtain:
```
Error:
String (`BODY_21A`) does not correspond to any model (BODY_25, COCO, MPI, MPI_4_layers).
```
If I try with BODY_25:

```
Error:
Person tracking (`--tracking` flag) is in experimental phase and only allows tracking of up to 1 person at the time. Please, also include the `--number_people_max 1` flag when using the `--tracking` flag. Tracking more than one person at the time is not expected as short- nor medium-term goal.
```

**Comment by dmetehan** [comment]
I'm having the same problem. Couldn't find a workaround yet.

**Comment by guerrifrancesco** [comment]
I switched to AlphaPose at the end. It has tracking and reidentification working out-of-the-box

**Comment by soulslicer** [comment]
you need to checkout the `STAF` branch and you have to download the model using `cd models; sh getModels.sh` it is all there in README

**Comment by dmetehan** [comment]
Thanks for the response. Could you add checking out to STAF branch into the README for people who forget it like us? 
Also another error I encountered was:
Check failed: error == cudaSuccess (700 vs. 0)  an illegal memory access was encountered
But I resolved it by adding --num_gpu 1 to my run command. I believe it's because the code doesn't support multiple GPUs.

Thanks again for making your code public.
